Improve switch diagnostic to emit the "jump" message on the specific bad case instead of on the switch.  Putting it on the switch means you don't know what case is the problem. For example:
scope-check.c:54:3: error: illegal switch case into protected scope
  case 2:
  ^
scope-check.c:53:9: note: jump bypasses initialization of variable length array
    int a[x];
        ^