--- Reverse-merging (from foreign repository) r73554 into '.': U    gcc/Makefile.in
Back-out patch. It was causing a bootstrap failure in Apple-style build:

Undefined symbols:
  "__ZN4llvm19InitializeARMAsmPrinterEv", referenced from:
  "__ZN4llvm19InitializePowerPCTargetEv", referenced from:
  "__ZN4llvm19InitializePowerPCAsmPrinterEv", referenced from:
  "__ZN4llvm19InitializeX86AsmPrinterEv", referenced from:
ld: symbol(s) not found
collect2: ld returned 1 exit status