Merge r105221: -- Author: Douglas Gregor <dgregor@apple.com> Date:   Mon May 31 14:40:22 2010 +0000
    When we see the a '[' in a postfix expression in Objective-C, perform
    a simple, quick check to determine whether the expression starting
    with '[' can only be an Objective-C message send. If so, don't parse
    it as an array subscript expression. This improves recovery for, e.g.,

      [a method1]
      [a method2]

    so that we now produce

      t.m:10:13: error: expected ';' after expression
      [a method]
                ^

    instead of some mess about expecting ']'.